import type { Owner, Application, PainPoint, SystemMetrics, PoolMember, CommunityEvent, TruckStop } from './types'

export const seedOwners: Owner[] = [
  {
    id: 'o1',
    name: 'Maria Schenk',
    initials: 'MS',
    role: 'Internal Lead',
    department: 'Production AI',
    implementations: 2,
    startupsOwned: 4,
    avgDaysToSignal: 10,
    connectionsThisQuarter: 9,
  },
  {
    id: 'o2',
    name: 'Tobias Frank',
    initials: 'TF',
    role: 'Internal Lead',
    department: 'Quality Systems',
    implementations: 1,
    startupsOwned: 3,
    avgDaysToSignal: 12,
    connectionsThisQuarter: 7,
  },
  {
    id: 'o3',
    name: 'Lukas Reinhardt',
    initials: 'LR',
    role: 'Internal Lead',
    department: 'Innovation & Ventures',
    implementations: 3,
    startupsOwned: 5,
    avgDaysToSignal: 9,
    connectionsThisQuarter: 11,
  },
  {
    id: 'o4',
    name: 'Priya Mehta',
    initials: 'PM',
    role: 'Internal Lead',
    department: 'Logistics & Supply',
    implementations: 1,
    startupsOwned: 2,
    avgDaysToSignal: 13,
    connectionsThisQuarter: 5,
  },
]

export const seedApplications: Application[] = [
  {
    id: 'APP-2024-0047',
    founderId: 'f1',
    founderName: 'Jonas Weber',
    founderInitials: 'JW',
    companyName: 'VisionQual',
    technology: 'AI quality inspection for production lines',
    stage: 'in_review',
    submittedAt: '2026-05-24',
    daysInProcess: 9,
    ownerId: 'o2',
    signalDeadline: '2026-06-07',
    notes: 'Deep-tech AI, strong traction in automotive adjacent markets. €800K seed.',
    funding: '€800K seed',
    teamSize: 6,
  },
  {
    id: 'APP-2024-0031',
    founderId: 'f2',
    founderName: 'Sarah Bauer',
    founderInitials: 'SB',
    companyName: 'FlowRoute',
    technology: 'Predictive logistics routing for OEM supply chains',
    stage: 'decision_go',
    submittedAt: '2026-05-07',
    daysInProcess: 26,
    ownerId: 'o4',
    signalDeadline: '2026-05-21',
    notes: 'Strong match with logistics pain points. Decision: Go.',
    funding: '€1.2M seed',
    teamSize: 9,
  },
  {
    id: 'APP-2024-0052',
    founderId: 'f3',
    founderName: 'Nico Hartmann',
    founderInitials: 'NH',
    companyName: 'CarbonLens',
    technology: 'Real-time carbon footprint tracking per vehicle model',
    stage: 'named_contact',
    submittedAt: '2026-06-01',
    daysInProcess: 1,
    ownerId: null,
    signalDeadline: '2026-06-15',
    notes: 'Just submitted. Named contact assigned within 48h.',
    funding: '€400K pre-seed',
    teamSize: 4,
  },
  {
    id: 'APP-2024-0029',
    founderId: 'f4',
    founderName: 'Elena Vogel',
    founderInitials: 'EV',
    companyName: 'SonoSense',
    technology: 'Ultrasonic structural integrity sensors for body manufacturing',
    stage: 'decision_redirect',
    submittedAt: '2026-05-01',
    daysInProcess: 32,
    ownerId: 'o1',
    signalDeadline: '2026-05-15',
    notes: 'Redirected — strong tech but outside current production roadmap. Referred to Tier 1 partner.',
    funding: '€600K seed',
    teamSize: 5,
  },
  {
    id: 'APP-2024-0058',
    founderId: 'f5',
    founderName: 'Daniel Kim',
    founderInitials: 'DK',
    companyName: 'GridMind',
    technology: 'AI-driven energy load balancing for factory floors',
    stage: 'owner_assigned',
    submittedAt: '2026-05-29',
    daysInProcess: 4,
    ownerId: 'o3',
    signalDeadline: '2026-06-12',
    notes: 'Internal Lead assigned. Initial call scheduled.',
    funding: '€550K pre-seed',
    teamSize: 7,
  },
  {
    id: 'APP-2026-0061',
    founderId: 'f6',
    founderName: 'Mara Lindqvist',
    founderInitials: 'ML',
    companyName: 'TorqueIQ',
    technology: 'Real-time torque telemetry and drift detection for assembly lines',
    stage: 'in_review',
    submittedAt: '2026-05-14',
    daysInProcess: 19,
    ownerId: 'o3',
    signalDeadline: '2026-05-28',
    notes: 'Past the 2-week mark with no decision. Internal Lead review stalled — needs a yes or no.',
    funding: '€700K seed',
    teamSize: 8,
  },
]

export const seedPainPoints: PainPoint[] = [
  {
    id: 'pp1',
    title: 'Manual visual inspection slowing production line throughput',
    description: 'Current visual QC is fully manual — 2 inspectors per shift, 4-second dwell per unit. At 1,200 units/day we are the bottleneck. We need automated detection with < 1s cycle time.',
    submittedBy: 'Tobias Frank',
    department: 'Quality',
    status: 'matched',
    linkedApplicationId: 'APP-2024-0047',
    submittedAt: '2026-05-20',
  },
  {
    id: 'pp2',
    title: 'No cross-department visibility into active pilot projects',
    description: 'Three departments are running parallel pilots with overlapping vendors. No shared register. We discovered duplicates in a hallway conversation — not a system.',
    submittedBy: 'Lukas Reinhardt',
    department: 'Innovation & Ventures',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-05-28',
  },
  {
    id: 'pp3',
    title: 'Inbound logistics routing adds 18h avg delay per delivery',
    description: 'Static routing tables haven\'t been updated since 2021. Dynamic traffic + supplier shifts cause systematic delay. Need ML-based adaptive routing.',
    submittedBy: 'Priya Mehta',
    department: 'Logistics',
    status: 'matched',
    linkedApplicationId: 'APP-2024-0031',
    submittedAt: '2026-05-15',
  },
  {
    id: 'pp4',
    title: 'Carbon accounting is manual and quarter-lagged',
    description: 'Sustainability reporting is done via spreadsheet, quarterly. Regulatory pressure is moving to real-time per-model disclosure. We have no tooling.',
    submittedBy: 'Anna Richter',
    department: 'R&D',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-05-30',
  },
  {
    id: 'pp5',
    title: 'Factory energy peaks not predicted — reactive grid management',
    description: 'Energy load spikes during line changeovers are unpredictable. We pay premium rates and occasionally trigger grid stress events. Predictive load balancing would cut costs ~12%.',
    submittedBy: 'Marco Benz',
    department: 'Production',
    status: 'in_pilot',
    linkedApplicationId: 'APP-2024-0058',
    submittedAt: '2026-05-18',
  },
  {
    id: 'pp6',
    title: 'Supplier qualification process takes 9 weeks — kills early-stage pilots',
    description: 'Standard procurement onboarding was designed for Tier 1s. Startups fail the financial history check. We need a fast-track track for < 12-month pilots.',
    submittedBy: 'Felix Wagner',
    department: 'Procurement',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-05-29',
  },
  {
    id: 'pp7',
    title: 'Body-weld integrity checks require destructive sampling',
    description: 'We currently sacrifice 3 units/day for structural integrity validation. Non-destructive alternatives (ultrasonic) exist but we have no internal testing infrastructure.',
    submittedBy: 'Sabine Keller',
    department: 'Production',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-06-01',
  },
  {
    id: 'pp8',
    title: 'R&D prototype feedback loop takes 6 weeks per iteration',
    description: 'Physical prototype sign-off requires cross-functional sign-off across 4 departments. Digital twin validation could compress this to days. No budget path for that tooling yet.',
    submittedBy: 'Hans Müller',
    department: 'R&D',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-06-02',
  },
]

export const seedPoolMembers: PoolMember[] = [
  {
    id: 'pm1',
    name: 'Elena Vogel',
    company: 'SonoSense',
    type: 'startup',
    techArea: 'Ultrasonic structural integrity sensors',
    addedAt: '2026-05-16',
    addedByName: 'Maria Schenk',
    applicationId: 'APP-2024-0029',
    notes: 'Your technology is strong, the timing didn\'t fit the current production roadmap. We referred you to a Tier 1 partner. Body-weld integrity is still an open pain point, and you\'re invited to all BRIDGE events.',
  },
  {
    id: 'pm2',
    name: 'Kai Bergmann',
    type: 'contact',
    techArea: 'Automotive AI & Tier 1 partner networks',
    addedAt: '2026-05-30',
    addedByName: 'Lukas Reinhardt',
    notes: 'Automotive AI consultant with strong Tier 1 supplier relationships. Can broker introductions between BRIDGE startups and procurement. Not an applicant — a connector.',
  },
]

export const seedCommunityEvents: CommunityEvent[] = [
  {
    id: 'evt1',
    title: 'Startup Open Day — Ingolstadt',
    date: '2026-07-10',
    location: 'Audi Forum, Ingolstadt',
    description: 'Meet Audi innovation leads and fellow community members. Live demos of current pilot projects. Open floor for new problem pitches.',
    type: 'networking',
    invitedMemberIds: ['pm1', 'pm2'],
  },
  {
    id: 'evt2',
    title: 'Deep Tech Workshop: Manufacturing Sensing',
    date: '2026-08-05',
    location: 'Production Hall B4 (restricted access)',
    description: 'Hands-on session inside the production line. Community startups with sensing or inspection technology get direct exposure to the real environment and current pain points.',
    type: 'workshop',
    invitedMemberIds: ['pm1'],
  },
  {
    id: 'evt3',
    title: 'Corporate Campus Challenge #7 — Demo Day',
    date: '2026-09-18',
    location: 'Audi Forum, Ingolstadt',
    description: 'Annual CCC demo day. Community members are invited as observers and future applicants. Watch the current cohort present to Audi leadership.',
    type: 'demo_day',
    invitedMemberIds: ['pm1', 'pm2'],
  },
  {
    id: 'evt4',
    title: 'BRIDGE Build Sprint — 24h Hackathon',
    date: '2026-08-22',
    location: 'Digital Hub, Munich',
    description: 'Overnight hackathon where community startups team up with Audi engineers to prototype against a live production pain point. Hardware and compute provided.',
    type: 'hackathon',
    invitedMemberIds: ['pm1', 'pm2'],
  },
  {
    id: 'evt5',
    title: 'Procurement Fast-Track Workshop',
    date: '2026-07-24',
    location: 'Audi Forum, Ingolstadt',
    description: 'Hands-on session on the startup procurement fast-track: how to pass qualification for a sub-12-month pilot without the Tier 1 financial history check.',
    type: 'workshop',
    invitedMemberIds: ['pm1', 'pm2'],
  },
  {
    id: 'evt6',
    title: 'Founders & Leads Mixer',
    date: '2026-07-03',
    location: 'Audi Forum, Ingolstadt',
    description: 'Informal evening connecting community founders with internal leads across Production, Quality, Logistics and R&D. Bring a one-line problem statement.',
    type: 'networking',
    invitedMemberIds: ['pm2'],
  },
  {
    id: 'evt-autobahn',
    title: 'STARTUP AUTOBAHN Expo Day — 10th Anniversary',
    date: '2026-07-02',
    location: 'Porsche Museum, Stuttgart',
    description: 'OEM–startup matchmaking at STARTUP AUTOBAHN\'s 15th edition. 1,800+ invited guests from across the automotive supply chain. BRIDGE community members get access to the Audi innovation booth and direct intro to pilot leads on-site.',
    type: 'networking',
    invitedMemberIds: ['pm1', 'pm2'],
  },
  {
    id: 'evt-bitsandpretzels',
    title: 'Bits & Pretzels — Founders Festival',
    date: '2026-09-28',
    location: 'ICM München, Munich',
    description: 'Europe\'s premier founder–investor festival: 7,500 attendees, 21,000 founder–investor meetings. BRIDGE hosts a side session on corporate pilot programmes — community members can join and connect with the broader VC network.',
    type: 'networking',
    invitedMemberIds: ['pm1', 'pm2'],
  },
]

export const seedTruckStops: TruckStop[] = [
  {
    id: 'ts1',
    city: 'Aachen',
    venue: 'RWTH Aachen — Collective Incubator',
    date: '2026-05-12',
    x: 2.3,
    y: 54.9,
    status: 'past',
    description: 'Kicked off the BRIDGE recruiting tour at RWTH. 40+ deep-tech teams pitched; 3 invited to apply.',
  },
  {
    id: 'ts4',
    city: 'Stuttgart',
    venue: 'University of Stuttgart — ARENA2036',
    date: '2026-05-28',
    x: 36.1,
    y: 80.6,
    status: 'past',
    description: 'Manufacturing and sensing day at the ARENA2036 research campus. Strong turnout from hardware teams at the demo bay.',
  },
  {
    id: 'ts-heilbronn',
    city: 'Heilbronn',
    venue: 'TUM Campus Heilbronn — Bildungscampus / IPAI',
    date: '2026-06-25',
    x: 36.4,
    y: 76.0,
    status: 'current',
    description: 'The truck is here now at the Innovation Park AI. Drop in for a 1:1 with a BRIDGE lead — no idea or pitch required, just a first conversation.',
    registerUrl: 'https://bridge.audi/tour/heilbronn',
  },
  {
    id: 'ts3',
    city: 'Munich',
    venue: 'TUM — UnternehmerTUM, Garching',
    date: '2026-07-09',
    x: 62.3,
    y: 88.8,
    status: 'upcoming',
    description: 'Open scouting day with UnternehmerTUM founders. The truck demos live pain points from the Ingolstadt production line.',
    registerUrl: 'https://bridge.audi/tour/munich',
  },
  {
    id: 'ts5',
    city: 'Dresden',
    venue: 'TU Dresden — dresden|exists',
    date: '2026-07-16',
    x: 85.8,
    y: 51.5,
    status: 'upcoming',
    description: 'Microelectronics and materials scouting stop in the Silicon Saxony cluster.',
    registerUrl: 'https://bridge.audi/tour/dresden',
  },
  {
    id: 'ts2',
    city: 'Berlin',
    venue: 'TU Berlin — Centre for Entrepreneurship',
    date: '2026-07-23',
    x: 82.1,
    y: 32.6,
    status: 'upcoming',
    description: 'AI and mobility startup meetup, hosted at the Centre for Entrepreneurship.',
    registerUrl: 'https://bridge.audi/tour/berlin',
  },
  {
    id: 'ts6',
    city: 'Hamburg',
    venue: 'Hamburg — Startup Dock, TUHH',
    date: '2026-07-30',
    x: 44.9,
    y: 19.4,
    status: 'upcoming',
    description: 'Final northern stop of the summer tour. Logistics and supply-chain startups especially welcome.',
    registerUrl: 'https://bridge.audi/tour/hamburg',
  },
  {
    id: 'ts-hannover',
    city: 'Hannover',
    venue: 'Hannover Messe — Deutsche Messe AG',
    date: '2026-04-22',
    x: 42.1,
    y: 34.5,
    status: 'past',
    description: 'BRIDGE scouted 4,000+ exhibitors at Europe\'s largest industrial tech expo. Key focus: AI-driven automation and energy infrastructure startups — 6 teams flagged for follow-up.',
  },
  {
    id: 'ts-freiburg',
    city: 'Freiburg',
    venue: 'Käpsele Innovation Festival — Konzerthaus Freiburg',
    date: '2026-07-16',
    x: 21.6,
    y: 90.6,
    status: 'upcoming',
    description: 'Largest innovation festival in southwest Germany. BRIDGE joins the GreenTech and deep-tech tracks — drop in at the BRIDGE booth to discuss open pain points from the Ingolstadt line.',
    registerUrl: 'https://bridge.audi/tour/freiburg',
  },
]

export const seedMetrics: SystemMetrics = {
  activePilots: 27,
  implementations: 3,
  avgTimeToSignal: 11,
  targetTimeToSignal: 14,
  connectionsThisQuarter: 32,
  implementationsThisQuarter: 3,
}
