import type { Owner, Application, PainPoint, SystemMetrics, PoolMember, CommunityEvent } from './types'

export const seedOwners: Owner[] = [
  {
    id: 'o1',
    name: 'Maria Schenk',
    initials: 'MS',
    role: 'Internal Lead',
    department: 'Production AI',
    implementations: 2,
    startupsOwned: 4,
    avgDaysToSignal: 10,
    connectionsThisQuarter: 9,
  },
  {
    id: 'o2',
    name: 'Tobias Frank',
    initials: 'TF',
    role: 'Internal Lead',
    department: 'Quality Systems',
    implementations: 1,
    startupsOwned: 3,
    avgDaysToSignal: 12,
    connectionsThisQuarter: 7,
  },
  {
    id: 'o3',
    name: 'Lukas Reinhardt',
    initials: 'LR',
    role: 'Internal Lead',
    department: 'Innovation & Ventures',
    implementations: 3,
    startupsOwned: 5,
    avgDaysToSignal: 9,
    connectionsThisQuarter: 11,
  },
  {
    id: 'o4',
    name: 'Priya Mehta',
    initials: 'PM',
    role: 'Internal Lead',
    department: 'Logistics & Supply',
    implementations: 1,
    startupsOwned: 2,
    avgDaysToSignal: 13,
    connectionsThisQuarter: 5,
  },
]

export const seedApplications: Application[] = [
  {
    id: 'APP-2024-0047',
    founderId: 'f1',
    founderName: 'Jonas Weber',
    founderInitials: 'JW',
    companyName: 'VisionQual',
    technology: 'AI quality inspection for production lines',
    stage: 'in_review',
    submittedAt: '2026-05-24',
    daysInProcess: 9,
    ownerId: 'o2',
    signalDeadline: '2026-06-07',
    notes: 'Deep-tech AI, strong traction in automotive adjacent markets. €800K seed.',
    funding: '€800K seed',
    teamSize: 6,
  },
  {
    id: 'APP-2024-0031',
    founderId: 'f2',
    founderName: 'Sarah Bauer',
    founderInitials: 'SB',
    companyName: 'FlowRoute',
    technology: 'Predictive logistics routing for OEM supply chains',
    stage: 'decision_go',
    submittedAt: '2026-05-07',
    daysInProcess: 26,
    ownerId: 'o4',
    signalDeadline: '2026-05-21',
    notes: 'Strong match with logistics pain points. Decision: Go.',
    funding: '€1.2M seed',
    teamSize: 9,
  },
  {
    id: 'APP-2024-0052',
    founderId: 'f3',
    founderName: 'Nico Hartmann',
    founderInitials: 'NH',
    companyName: 'CarbonLens',
    technology: 'Real-time carbon footprint tracking per vehicle model',
    stage: 'named_contact',
    submittedAt: '2026-06-01',
    daysInProcess: 1,
    ownerId: null,
    signalDeadline: '2026-06-15',
    notes: 'Just submitted. Named contact assigned within 48h.',
    funding: '€400K pre-seed',
    teamSize: 4,
  },
  {
    id: 'APP-2024-0029',
    founderId: 'f4',
    founderName: 'Elena Vogel',
    founderInitials: 'EV',
    companyName: 'SonoSense',
    technology: 'Ultrasonic structural integrity sensors for body manufacturing',
    stage: 'decision_redirect',
    submittedAt: '2026-05-01',
    daysInProcess: 32,
    ownerId: 'o1',
    signalDeadline: '2026-05-15',
    notes: 'Redirected — strong tech but outside current production roadmap. Referred to Tier 1 partner.',
    funding: '€600K seed',
    teamSize: 5,
  },
  {
    id: 'APP-2024-0058',
    founderId: 'f5',
    founderName: 'Daniel Kim',
    founderInitials: 'DK',
    companyName: 'GridMind',
    technology: 'AI-driven energy load balancing for factory floors',
    stage: 'owner_assigned',
    submittedAt: '2026-05-29',
    daysInProcess: 4,
    ownerId: 'o3',
    signalDeadline: '2026-06-12',
    notes: 'Internal Lead assigned. Initial call scheduled.',
    funding: '€550K pre-seed',
    teamSize: 7,
  },
  {
    id: 'APP-2026-0061',
    founderId: 'f6',
    founderName: 'Mara Lindqvist',
    founderInitials: 'ML',
    companyName: 'TorqueIQ',
    technology: 'Real-time torque telemetry and drift detection for assembly lines',
    stage: 'in_review',
    submittedAt: '2026-05-14',
    daysInProcess: 19,
    ownerId: 'o3',
    signalDeadline: '2026-05-28',
    notes: 'Past the 2-week mark with no decision. Internal Lead review stalled — needs a yes or no.',
    funding: '€700K seed',
    teamSize: 8,
  },
]

export const seedPainPoints: PainPoint[] = [
  {
    id: 'pp1',
    title: 'Manual visual inspection slowing production line throughput',
    description: 'Current visual QC is fully manual — 2 inspectors per shift, 4-second dwell per unit. At 1,200 units/day we are the bottleneck. We need automated detection with < 1s cycle time.',
    submittedBy: 'Tobias Frank',
    department: 'Quality',
    status: 'matched',
    linkedApplicationId: 'APP-2024-0047',
    submittedAt: '2026-05-20',
  },
  {
    id: 'pp2',
    title: 'No cross-department visibility into active pilot projects',
    description: 'Three departments are running parallel pilots with overlapping vendors. No shared register. We discovered duplicates in a hallway conversation — not a system.',
    submittedBy: 'Lukas Reinhardt',
    department: 'Innovation & Ventures',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-05-28',
  },
  {
    id: 'pp3',
    title: 'Inbound logistics routing adds 18h avg delay per delivery',
    description: 'Static routing tables haven\'t been updated since 2021. Dynamic traffic + supplier shifts cause systematic delay. Need ML-based adaptive routing.',
    submittedBy: 'Priya Mehta',
    department: 'Logistics',
    status: 'matched',
    linkedApplicationId: 'APP-2024-0031',
    submittedAt: '2026-05-15',
  },
  {
    id: 'pp4',
    title: 'Carbon accounting is manual and quarter-lagged',
    description: 'Sustainability reporting is done via spreadsheet, quarterly. Regulatory pressure is moving to real-time per-model disclosure. We have no tooling.',
    submittedBy: 'Anna Richter',
    department: 'R&D',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-05-30',
  },
  {
    id: 'pp5',
    title: 'Factory energy peaks not predicted — reactive grid management',
    description: 'Energy load spikes during line changeovers are unpredictable. We pay premium rates and occasionally trigger grid stress events. Predictive load balancing would cut costs ~12%.',
    submittedBy: 'Marco Benz',
    department: 'Production',
    status: 'in_pilot',
    linkedApplicationId: 'APP-2024-0058',
    submittedAt: '2026-05-18',
  },
  {
    id: 'pp6',
    title: 'Supplier qualification process takes 9 weeks — kills early-stage pilots',
    description: 'Standard procurement onboarding was designed for Tier 1s. Startups fail the financial history check. We need a fast-track track for < 12-month pilots.',
    submittedBy: 'Felix Wagner',
    department: 'Procurement',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-05-29',
  },
  {
    id: 'pp7',
    title: 'Body-weld integrity checks require destructive sampling',
    description: 'We currently sacrifice 3 units/day for structural integrity validation. Non-destructive alternatives (ultrasonic) exist but we have no internal testing infrastructure.',
    submittedBy: 'Sabine Keller',
    department: 'Production',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-06-01',
  },
  {
    id: 'pp8',
    title: 'R&D prototype feedback loop takes 6 weeks per iteration',
    description: 'Physical prototype sign-off requires cross-functional sign-off across 4 departments. Digital twin validation could compress this to days. No budget path for that tooling yet.',
    submittedBy: 'Hans Müller',
    department: 'R&D',
    status: 'open',
    linkedApplicationId: null,
    submittedAt: '2026-06-02',
  },
]

export const seedPoolMembers: PoolMember[] = [
  {
    id: 'pm1',
    name: 'Elena Vogel',
    company: 'SonoSense',
    type: 'startup',
    techArea: 'Ultrasonic structural integrity sensors',
    addedAt: '2026-05-16',
    addedByName: 'Maria Schenk',
    applicationId: 'APP-2024-0029',
    notes: 'Your technology is strong, the timing didn\'t fit the current production roadmap. We referred you to a Tier 1 partner. Body-weld integrity is still an open pain point, and you\'re invited to all BRIDGE events.\n\nA no today is not a no forever.',
  },
  {
    id: 'pm2',
    name: 'Kai Bergmann',
    type: 'contact',
    techArea: 'Automotive AI & Tier 1 partner networks',
    addedAt: '2026-05-30',
    addedByName: 'Lukas Reinhardt',
    notes: 'Automotive AI consultant with strong Tier 1 supplier relationships. Can broker introductions between BRIDGE startups and procurement. Not an applicant — a connector.',
  },
]

export const seedCommunityEvents: CommunityEvent[] = [
  {
    id: 'evt1',
    title: 'Startup Open Day — Ingolstadt',
    date: '2026-07-10',
    location: 'Audi Forum, Ingolstadt',
    description: 'Meet Audi innovation leads and fellow community members. Live demos of current pilot projects. Open floor for new problem pitches.',
    type: 'networking',
    invitedMemberIds: ['pm1', 'pm2'],
  },
  {
    id: 'evt2',
    title: 'Deep Tech Workshop: Manufacturing Sensing',
    date: '2026-08-05',
    location: 'Production Hall B4 (restricted access)',
    description: 'Hands-on session inside the production line. Community startups with sensing or inspection technology get direct exposure to the real environment and current pain points.',
    type: 'workshop',
    invitedMemberIds: ['pm1'],
  },
  {
    id: 'evt3',
    title: 'Corporate Campus Challenge #7 — Demo Day',
    date: '2026-09-18',
    location: 'Audi Forum, Ingolstadt',
    description: 'Annual CCC demo day. Community members are invited as observers and future applicants. Watch the current cohort present to Audi leadership.',
    type: 'demo_day',
    invitedMemberIds: ['pm1', 'pm2'],
  },
]

export const seedMetrics: SystemMetrics = {
  activePilots: 27,
  implementations: 3,
  avgTimeToSignal: 11,
  targetTimeToSignal: 14,
  connectionsThisQuarter: 32,
  implementationsThisQuarter: 3,
}
